apiVersion: v1
kind: Pod
metadata:
  name: user-management
  labels:
    env: dev
    app: user-management
spec:
  containers:
    - name: user-management
      image: alpine
      ports:
        - containerPort: 8090
